# Generated by Django 5.0.3 on 2024-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(max_length=255)),
                ('transcript_text', models.TextField()),
            ],
        ),
    ]
